=== knappema/XML_Nahverkehr/XML_Nahverkehr/src/xml_nahverkehr/nv_drivers.dtd
<!ELEMENT dr:drivers (dr:driver*)>

<!ELEMENT dr:driver (dr:vehicle+, dr:homeaddress)>
<!ATTLIST dr:driver firstname CDATA #REQUIRED
lastname CDATA #REQUIRED
phone CDATA #REQUIRED
driverId ID #REQUIRED>

<!ELEMENT dr:vehicle EMPTY>
<!ATTLIST dr:vehicle type CDATA #REQUIRED>

<!ELEMENT dr:homeaddress (dr:street, dr:houseNo, dr:areacode, dr:town)>

<!ELEMENT dr:street (#PCDATA)>

<!ELEMENT dr:houseNo (#PCDATA)>

<!ELEMENT dr:areacode (#PCDATA)>

<!ELEMENT dr:town (#PCDATA)>

=== knappema/XML_Nahverkehr/XML_Nahverkehr/src/xml_nahverkehr/nv_drivers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehicles SYSTEM "nv_drivers.dtd">

<drivers>
	<driver firstname="Tim" lastname="Test" phone="01605678945">
		<vehicle>tram</vehicle>
		<vehicle>subway</vehicle>
		<homeadress>
			<street>Rieterstraße</street>
			<houseNo>100</houseNo>
			<areacode>90530</areacode>
			<town>Wendelstein</town>
		</homeadress>
	</driver>
</drivers>
