=== knappema/XML_Nahverkehr/XML_Nahverkehr/src/xml_nahverkehr/nv_stations.dtd
<!ELEMENT stations (station*)>

<!ELEMENT station (stationTypes, street, intersection?,  ticketMachines?)>
<!ATTLIST station stationId ID #REQUIRED
name CDATA #REQUIRED>

<!ELEMENT stationTypes (type+)>

<!ELEMENT type EMPTY>
<!ATTLIST type name (bus | tram | subway | city_train) #REQUIRED>

<!ELEMENT street EMPTY>
<!ATTLIST street name CDATA #REQUIRED>

<!ELEMENT ticketMachines (ticketMachine+)>

<!ELEMENT ticketMachine EMPTY>
<!ATTLIST ticketMachine id ID #REQUIRED>

=== knappema/XML_Nahverkehr/XML_Nahverkehr/src/xml_nahverkehr/nv_stations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehicles SYSTEM "nv_stations.dtd">

<stations>
    <station name="Hauptbahnhof">
        <stationTypes>
            <type name="bus"/>
            <type name="subway"/>
			<type name="tram" />
			<type name="city_train" />
        </stationTypes>
        <street name="Bahnhofsplatz"/>
        <ticketMachines>
            <ticketMachine id="TM1" />
        </ticketMachines>
    </station>

</stations>
