=== knappema/XML_Nahverkehr/XML_Nahverkehr/src/xml_nahverkehr/nv_tickets.dtd
<!ELEMENT tickets (ticket*)>

<!ELEMENT ticket (description+, fares)>
<!ATTLIST ticket type (single | day | month) #REQUIRED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT fares (fare+)>

<!ELEMENT fare (A?, T2?, T3?, T4?)>
<!ATTLIST fare type CDATA #REQUIRED
price CDATA #REQUIRED>

=== knappema/XML_Nahverkehr/XML_Nahverkehr/src/xml_nahverkehr/nv_tickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehicles SYSTEM "nv_tickets.dtd">

<tickets>
	<ticket type="single">
		<description>Valid only for one trip</description>
		<fares>
			<fare type="A" price="2,50" />
			<fare type="T2" price="2,30" />
			<fare type="T3" price="3,20" />
			<fare type="T4" price="4,20" />
		</fares>
	</ticket>
	<ticket type="day">
		<description>Valid for remaining day or remaining weekend</description>
		<fares>
			<fare type="A" price="5,30" />
			<fare type="T2" price="4,60" />
			<fare type="T3" price="11,00" />
			<fare type="T4" price="11,00" />
		</fares>
	</ticket>
	<ticket type="month">
		<description>Valid from first day of a month until the last day of the same month </description>
		<fares>
			<fare type="A" price="49,40" />
			<fare type="T2" price="46,60" />
			<fare type="T3" price="62,10" />
			<fare type="T4" price="80,40" />
		</fares>
	</ticket>
</tickets>
